export default function Education(){
 return <div className="container form-shell"><div className="form-head"><span className="kicker">Edukasi preventif</span><h2>Kenali indikator pertumbuhan dengan benar</h2><p className="lead">Konten ini mendukung tujuan skripsi: membantu masyarakat membedakan stunting dari kondisi gizi lain dan mendorong pemantauan pertumbuhan rutin.</p></div>
 <div className="grid-2">
  <article className="article"><h3>Apa itu stunting?</h3><p>Stunting adalah kondisi ketika panjang/tinggi badan menurut umur berada sangat rendah dibandingkan standar pertumbuhan. Penilaian tidak dilakukan dari berat badan saja.</p><ul><li>Indikator utama: panjang/tinggi badan menurut umur.</li><li>Ambang yang umum digunakan: di bawah −2 SD standar WHO.</li><li>Pengukuran perlu dilakukan dengan teknik dan alat yang benar.</li></ul></article>
  <article className="article"><h3>Stunting vs underweight</h3><p>Underweight menilai berat badan menurut umur. Seorang anak dapat underweight tanpa stunting, stunting tanpa underweight, atau mengalami keduanya.</p><ul><li>Stunting → tinggi/panjang menurut umur.</li><li>Underweight → berat menurut umur.</li><li>Karena indikator berbeda, hasil tidak boleh disimpulkan dari tampilan fisik saja.</li></ul></article>
  <article className="article"><h3>1000 hari pertama kehidupan</h3><p>Masa sejak kehamilan sampai sekitar usia dua tahun adalah periode penting bagi pertumbuhan dan perkembangan. Pemantauan pertumbuhan, kesehatan, dan asupan gizi perlu dilakukan secara konsisten.</p></article>
  <article className="article"><h3>Kapan perlu mencari bantuan?</h3><p>Jika hasil screening berada pada kategori sedang/tinggi, pengukuran tampak tidak sesuai, pertumbuhan melambat, atau orang tua memiliki kekhawatiran lain, lakukan pemeriksaan ke Posyandu, Puskesmas, dokter, atau tenaga gizi.</p></article>
 </div><div className="notice" style={{marginTop:20}}>Konten website bersifat edukasi umum dan tidak menggantikan pemeriksaan klinis, diagnosis, maupun rencana terapi individual.</div>
 </div>
}
